# Generated by Django 2.2.4 on 2019-08-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_api', '0002_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='symptom',
        ),
        migrations.AddField(
            model_name='symptom',
            name='results',
            field=models.ManyToManyField(to='healthcare_api.Result'),
        ),
    ]
